/* Test engine thi thử LiD. Chạy: node test/lid-exam.test.cjs */
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const store = new Map();
globalThis.localStorage = { getItem: (k) => (store.has(k) ? store.get(k) : null), setItem: (k, v) => store.set(k, String(v)), removeItem: (k) => store.delete(k) };
globalThis.window = globalThis.window || {};
eval(fs.readFileSync(path.join(__dirname, '..', 'lid', 'lid-exam.js'), 'utf8'));
const E = window.LidExam;
assert.strictEqual(E.PASS_MARK, 17);
assert.strictEqual(E.PAPER_N, 33);
assert.strictEqual(E.TIME_S, 3600);
assert.strictEqual(E.getLand(), 'BY');
E.setLand('BE');
assert.strictEqual(E.getLand(), 'BE');
E.setLand('XX');
assert.strictEqual(E.getLand(), 'BY');
const fake = [];
for (let i = 0; i < 300; i++) fake.push({ theme: 'lid-demo', cat: 'c', land: null, q: 'q' + i, opts: ['a','b','c','d'], a: 0, ex: 'e' });
for (let i = 0; i < 10; i++) fake.push({ theme: 'lid-land-BE', cat: 'Berlin', land: 'BE', q: 'b' + i, opts: ['a','b','c','d'], a: 1, ex: 'e' });
for (let i = 0; i < 10; i++) fake.push({ theme: 'lid-land-BY', cat: 'Bayern', land: 'BY', q: 'y' + i, opts: ['a','b','c','d'], a: 2, ex: 'e' });
const paper = E.buildLidPaper(fake, 'BE', () => 0.5);
assert.strictEqual(paper.length, 33);
assert.strictEqual(paper.filter((q) => q.land === 'BE').length, 3);
assert.strictEqual(paper.filter((q) => !q.land).length, 30);
const ans = paper.map((q, i) => (i < 17 ? q.a : (q.a + 1) % 4));
const r = E.lidScore(paper, ans);
assert.strictEqual(r.correct, 17);
assert.strictEqual(r.passed, true);
const r2 = E.lidScore(paper, paper.map(() => null));
assert.strictEqual(r2.correct, 0);
assert.strictEqual(r2.passed, false);
assert.strictEqual(E.lidFormatTime(3599), '59:59');
assert.strictEqual(E.lidFormatTime(60), '01:00');
console.log('PASS lid-exam');
